name: CI

on:
    workflow_dispatch:
    workflow_call:
    pull_request:

permissions:
    checks: write
    contents: read

jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Formatting
              run: bun run format:check

            - name: Build
              run: bun run build

            - name: Linting
              run: bun run lint

            - name: 'Unit tests: common'
              run: npx zenfs-test -pfw --common

            - name: 'Unit tests: InMemory'
              run: npx zenfs-test -pfw tests/setup/memory.ts

            - name: 'Unit tests: contexts'
              run: npx zenfs-test -pfw tests/setup/context.ts

            - name: 'Unit tests: Copy-on-Write'
              run: npx zenfs-test -pfw tests/setup/cow.ts

            - name: 'Unit tests: Index'
              run: npx zenfs-test -pfw tests/setup/index.ts

            - name: 'Unit tests: Port'
              run: npx zenfs-test -pfw tests/setup/port.ts

            - name: 'Unit tests: SingleBuffer'
              run: npx zenfs-test -pfw tests/setup/single-buffer.ts

            - name: 'Unit tests: Fetch'
              run: tests/fetch/run.sh -w

            - name: Report coverage
              run: npx zenfs-test --report
