name: CI

on:
    push:
        branches:
            - main
    workflow_dispatch:
    workflow_call:

permissions:
    checks: write
    contents: read

jobs:
    ci:
        name: Continuous Integration
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - name: Install dependencies
              run: bun install

            - name: Create sub-checks
              run: bun zci init

            - name: Formatting
              run: bun zci run format "bun run format:check"

            - name: Build
              run: bun zci run build "bun run build"

            - name: Linting
              run: bun zci run lint "bun run lint"

            - name: 'Unit tests: common'
              run: bun zenfs-test -pfwC --common

            - name: 'Unit tests: InMemory'
              run: bun zenfs-test -pfwC tests/setup/memory.ts

            - name: 'Unit tests: Copy-On-Write'
              run: bun zenfs-test -pfwC tests/setup/cow.ts

            - name: 'Unit tests: contexts'
              run: bun zenfs-test -pfwC tests/setup/context.ts

            - name: 'Unit tests: Index'
              run: bun zenfs-test -pfwC tests/setup/index.ts

            - name: 'Unit tests: Port'
              run: bun zenfs-test -pfwC tests/setup/port.ts

            - name: 'Unit tests: SingleBuffer'
              run: bun zenfs-test -pfwC tests/setup/single-buffer.ts

            - name: 'Unit tests: Fetch'
              run: tests/fetch/run.sh -wC

            - name: Report coverage
              run: bun zenfs-test --report

            - name: Cleanup sub-checks
              if: always()
              run: bun zci cleanup
