name: Release

on:
    workflow_dispatch:
    release:
        types: [created]

jobs:
    ci:
        name: Test
        uses: ./.github/workflows/ci.yaml

    release:
        name: Publish
        needs: ci
        uses: ./.github/workflows/release-common.yaml
        with:
            to-location: 'https://registry.npmjs.org/'
        secrets: inherit
